### ISSUE TITLE
Regarding Internship at Origin Cloud Technologies 

### ISSUE THREAD

**Issue by stacknationorg** [varunsh17/Origin_cloud_Project#1]
Hi Varun,
I'm from Origin Cloud Technologies. We had issues with Internshala as we weren't able to reach out to candidates since 23rd may. If you're interested. Kindly drop an email

**Comment by varunsh17** [comment]
Yes I am interested , I also completed your project on time and submitted
it..
The link for that is - https://github.com/varunsh17/Origin_cloud_Project

**Comment by stacknationorg** [comment]
varunsh170502@gmail.com
Is this your mail?

**Comment by stacknationorg** [comment]
I've tried reaching out. No response over email & here. Maybe you're occupied and not much interested.

**Comment by varunsh17** [comment]
I have got a better internship offer, so I will go ahead with it. Thanks
for your concern.

**Comment by varunsh17** [comment]
Yes, it is.
